import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { getTool } from "../registry";
import { resetLordConfig } from "../config";
import { registerFileTools } from "./files";

let allowedDir = "";
let outsideDir = "";
let previousAllowedDirs: string | undefined;

beforeEach(() => {
  previousAllowedDirs = process.env.LORD_ALLOWED_DIRS;
  allowedDir = fs.mkdtempSync(path.join(os.tmpdir(), "lord-agent-allowed-"));
  outsideDir = fs.mkdtempSync(path.join(os.tmpdir(), "lord-agent-outside-"));
  process.env.LORD_ALLOWED_DIRS = JSON.stringify([allowedDir]);
  resetLordConfig();
  registerFileTools();
});

afterEach(() => {
  if (previousAllowedDirs === undefined) delete process.env.LORD_ALLOWED_DIRS;
  else process.env.LORD_ALLOWED_DIRS = previousAllowedDirs;
  resetLordConfig();
  fs.rmSync(allowedDir, { recursive: true, force: true });
  fs.rmSync(outsideDir, { recursive: true, force: true });
});

function context() {
  return { log: vi.fn() } as never;
}

describe("files.write_text", () => {
  it("writes text atomically within the configured allowed root", async () => {
    const tool = getTool("files.write_text");
    expect(tool?.risk).toBe("high");
    expect(tool?.requiresConfirmation).toBe(true);

    const result = await tool!.execute(
      { path: "App.tsx", content: "export default 1;" },
      context(),
    );

    expect(result.success).toBe(true);
    expect(fs.readFileSync(path.join(allowedDir, "App.tsx"), "utf8")).toBe("export default 1;");
  });

  it("rejects traversal, secret environment paths, and symlink escapes", async () => {
    const tool = getTool("files.write_text")!;
    const traversal = await tool.execute({ path: "../outside.ts", content: "x" }, context());
    const environmentFile = await tool.execute(
      { path: ".env.local", content: "SECRET=value" },
      context(),
    );
    fs.symlinkSync(outsideDir, path.join(allowedDir, "escape"), "dir");
    const symlinkEscape = await tool.execute(
      { path: "escape/payload.ts", content: "x" },
      context(),
    );

    expect(traversal.success).toBe(false);
    expect(environmentFile.success).toBe(false);
    expect(symlinkEscape.success).toBe(false);
    expect(fs.existsSync(path.join(outsideDir, "payload.ts"))).toBe(false);
  });

  it("protects generated files unless the confirmed plan explicitly allows them", async () => {
    const generatedDirectory = path.join(allowedDir, "src");
    fs.mkdirSync(generatedDirectory);
    const generatedFile = path.join(generatedDirectory, "routeTree.gen.ts");
    fs.writeFileSync(generatedFile, "// This file is automatically generated.\nexport {};\n");
    const tool = getTool("files.write_text")!;

    const denied = await tool.execute(
      { path: "src/routeTree.gen.ts", content: "export const route = true;" },
      context(),
    );
    const explicitlyAllowed = await tool.execute(
      {
        path: "src/routeTree.gen.ts",
        content: "export const route = true;",
        allowGenerated: true,
      },
      context(),
    );

    expect(denied).toMatchObject({ success: false, errorCode: "GENERATED_FILE_PROTECTED" });
    expect(explicitlyAllowed.success).toBe(true);
  });
});
