// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { Capacitor, registerPlugin } from "@capacitor/core";
import type { Database } from "./types";
import { createSupabaseAuthStorage, type NativeSecureStore } from "@/lib/supabase-auth-storage";

const SecureSessionStorage = registerPlugin<NativeSecureStore>("SecureSessionStorage");

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    process.env.SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY
        ? [
            "SUPABASE_PUBLISHABLE_KEY",
            "SUPABASE_ANON_KEY",
            "VITE_SUPABASE_PUBLISHABLE_KEY",
            "VITE_SUPABASE_ANON_KEY",
          ]
        : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (Capacitor.isNativePlatform()) {
    let supabaseEndpoint: URL;
    try {
      supabaseEndpoint = new URL(SUPABASE_URL);
    } catch {
      throw new Error("The Android app requires a valid HTTPS Supabase URL.");
    }
    if (supabaseEndpoint.protocol !== "https:") {
      throw new Error("The Android app requires Supabase connections to use HTTPS.");
    }
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: createSupabaseAuthStorage({
        native: Capacitor.isNativePlatform(),
        secure: Capacitor.isNativePlatform() ? SecureSessionStorage : undefined,
        local: typeof window !== "undefined" ? localStorage : undefined,
      }),
      detectSessionInUrl: true,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
